# Generated by Django 6.1 on 2026-08-23 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('displayName', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('kycVerified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('status', models.CharField(default='awaiting_acceptance', max_length=50)),
                ('escrowBalance', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_transactions', to='escrow.party')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_transactions', to='escrow.party')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('actorId', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='escrow.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='')),
                ('status', models.CharField(default='submitted', max_length=50)),
                ('uploadedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(blank=True, null=True)),
                ('verifiedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('verifiedAt', models.DateTimeField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='escrow.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('actor', models.CharField(max_length=255)),
                ('comment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_history', to='escrow.party')),
            ],
        ),
    ]
