# Generated by Django 6.1 on 2026-08-23 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0002_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='confirmedDeposits',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contractStatus',
            field=models.CharField(default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='disputeStatus',
            field=models.CharField(default='none', max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='expectedCompletionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='frozenAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fundingStatus',
            field=models.CharField(default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='kycStatus',
            field=models.CharField(default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='pendingRelease',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='refundedAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='releasedAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='requiredEscrowAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='riskStatus',
            field=models.CharField(default='low', max_length=32),
        ),
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(choices=[('general_escrow', 'General Escrow'), ('vehicle_purchase', 'Vehicle Purchase'), ('construction_project', 'Construction Project'), ('sme_procurement', 'SME Procurement'), ('goods_purchase', 'Goods Purchase'), ('professional_services', 'Professional Services'), ('freelance_services', 'Freelance Services'), ('property_transaction', 'Property Transaction')], default='general_escrow', max_length=64),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_counterparty_acceptance', 'Awaiting Counterparty Acceptance'), ('awaiting_kyc', 'Awaiting KYC'), ('contract_pending', 'Contract Pending'), ('awaiting_funding', 'Awaiting Funding'), ('funded', 'Funded'), ('in_progress', 'In Progress'), ('awaiting_verification', 'Awaiting Verification'), ('release_pending', 'Release Pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold'), ('disputed', 'Disputed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='draft', max_length=50),
        ),
    ]
