# Generated by Django 6.1 on 2026-08-23 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0003_transaction_confirmeddeposits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idType', models.CharField(choices=[('nin', 'National Identification Number'), ('passport', 'Passport'), ('drivers_license', "Driver's licence")], default='nin', max_length=32)),
                ('nin', models.CharField(blank=True, max_length=20)),
                ('idNumber', models.CharField(blank=True, max_length=64)),
                ('idImage', models.ImageField(upload_to='kyc/identification/')),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('verificationStatus', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('verificationChecks', models.JSONField(blank=True, default=dict)),
                ('providerReference', models.CharField(blank=True, max_length=128)),
                ('submittedAt', models.DateTimeField(auto_now_add=True)),
                ('verifiedAt', models.DateTimeField(blank=True, null=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_submission', to='escrow.party')),
            ],
        ),
    ]
