# Generated by Django 6.1 on 2026-08-23 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_transaction_profiles(apps, schema_editor):
    Party = apps.get_model('escrow', 'Party')
    UserProfile = apps.get_model('escrow', 'UserProfile')
    Transaction = apps.get_model('escrow', 'Transaction')

    for profile in UserProfile.objects.exclude(party_id=None).iterator():
        Party.objects.filter(pk=profile.party_id, user_id=None).update(user_id=profile.user_id)

    unresolved = []
    for transaction in Transaction.objects.all().iterator():
        buyer_profile = UserProfile.objects.filter(party_id=transaction.buyer_id).first() if transaction.buyer_id else None
        seller_profile = UserProfile.objects.filter(party_id=transaction.seller_id).first() if transaction.seller_id else None
        transaction.buyer_profile_id = buyer_profile.pk if buyer_profile else None
        transaction.seller_profile_id = seller_profile.pk if seller_profile else None
        transaction.save(update_fields=['buyer_profile', 'seller_profile'])
        if transaction.buyer_id and not buyer_profile:
            unresolved.append(f'{transaction.pk}: buyer {transaction.buyer_id}')
        if transaction.seller_id and not seller_profile:
            unresolved.append(f'{transaction.pk}: seller {transaction.seller_id}')
    if unresolved:
        print('Unresolved legacy transaction participants: ' + ', '.join(unresolved))


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0004_kycsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='party', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyer_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='escrow.userprofile'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='seller_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='escrow.userprofile'),
        ),
        migrations.RunPython(
            code=backfill_transaction_profiles,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='seller',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='buyer_profile',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='seller_profile',
            new_name='seller',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer_transactions', to='escrow.userprofile'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_transactions', to='escrow.userprofile'),
        ),
        migrations.CreateModel(
            name='TransactionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lawyer', 'Lawyer'), ('engineer', 'Engineer'), ('verifier', 'Verifier'), ('surveyor', 'Surveyor'), ('arbitrator', 'Arbitrator')], max_length=32)),
                ('assignedAt', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='escrow.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_assignments', to='escrow.userprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('transaction', 'user', 'role'), name='unique_transaction_participant_role')],
            },
        ),
    ]
