# Generated by Django 6.1 on 2026-08-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0005_transaction_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyerAcceptedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyerApprovedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyerReviewedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='buyerSignedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='contractGeneratedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deliveryVerifiedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fundingInitiatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fundsConfirmedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='releasedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sellerAcceptedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sellerDeliveredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sellerReviewedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sellerSignedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_party_review', 'Awaiting Party Review'), ('awaiting_buyer_acceptance', 'Awaiting Buyer Acceptance'), ('awaiting_seller_acceptance', 'Awaiting Seller Acceptance'), ('awaiting_kyc', 'Awaiting KYC'), ('contract_pending', 'Contract Pending'), ('awaiting_buyer_signature', 'Awaiting Buyer Signature'), ('awaiting_seller_signature', 'Awaiting Seller Signature'), ('awaiting_funding', 'Awaiting Funding'), ('funding_confirmation_pending', 'Funding Confirmation Pending'), ('funded', 'Funded'), ('in_progress', 'In Progress'), ('awaiting_verification', 'Awaiting Verification'), ('awaiting_buyer_approval', 'Awaiting Buyer Approval'), ('release_pending', 'Release Pending'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold'), ('disputed', 'Disputed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='draft', max_length=50),
        ),
    ]
