# Generated by Django 6.1 on 2026-08-23 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0007_normalize_workflow_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Escrow agreement', max_length=255)),
                ('content', models.TextField()),
                ('status', models.CharField(default='generated', max_length=32)),
                ('generatedAt', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='escrow.transaction')),
            ],
        ),
    ]
