# Generated by Django 6.1 on 2026-08-23 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0008_contract'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.CharField(default='supporting', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='checksum',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='generatedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='generatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='generated_transaction_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='referenceNumber',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='document',
            name='rejectionNotes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseding_documents', to='escrow.document'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploadedByUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_transaction_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='document',
            name='visibility',
            field=models.CharField(default='participants', max_length=32),
        ),
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionType', models.CharField(blank=True, default='', max_length=64)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('documentType', models.CharField(max_length=100)),
                ('category', models.CharField(default='supporting', max_length=100)),
                ('stage', models.CharField(default='delivery', max_length=64)),
                ('partyRole', models.CharField(default='seller', max_length=32)),
                ('required', models.BooleanField(default=True)),
                ('verificationRequired', models.BooleanField(default=False)),
                ('requiredVerifierRole', models.CharField(blank=True, max_length=64)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('transactionType', 'stage', 'label'),
                'constraints': [models.UniqueConstraint(fields=('transactionType', 'key'), name='unique_document_requirement_type_key')],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='requirement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='escrow.documentrequirement'),
        ),
        migrations.CreateModel(
            name='DocumentWorkflowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=64)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workflow_records', to='escrow.document')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escrow.documentrequirement')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_records', to='escrow.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('dueDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='proposed', max_length=32)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='escrow.transaction')),
            ],
            options={
                'ordering': ('sequence', 'id'),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='escrow.milestone'),
        ),
    ]
