# Generated by Django 6.1 on 2026-08-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0010_default_document_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='buyerSignatureMethod',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='buyerSignedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='sellerSignatureMethod',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='sellerSignedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
