# Generated by Django 6.1 on 2026-08-24 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0011_document_signatures'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('card_gateway', 'Card / payment gateway'), ('cash', 'Cash deposit')], max_length=32)),
                ('reference', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('confirmedAt', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('confirmedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='escrow.document')),
                ('submittedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_payments', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='escrow.transaction')),
            ],
        ),
    ]
