# Generated by Django 6.1 on 2026-08-24 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0012_payment_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='confirmedAmount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='externalReference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='valueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='channel',
            field=models.CharField(choices=[('bank_transfer', 'Bank transfer'), ('mobile_money', 'Mobile money'), ('card_gateway', 'Card / payment gateway'), ('cash_deposit', 'Cash deposit'), ('cash', 'Cash deposit')], max_length=32),
        ),
        migrations.AlterField(
            model_name='paymentrecord',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed'), ('refunded', 'Refunded')], default='submitted', max_length=20),
        ),
        migrations.CreateModel(
            name='EscrowLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryType', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('reference', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='escrow.paymentrecord')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='escrow.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=128, unique=True)),
                ('amountDue', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('bankName', models.CharField(blank=True, max_length=255)),
                ('accountDetails', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_instruction', to='escrow.transaction')),
            ],
        ),
    ]
