# Generated by Django 6.1 on 2026-08-24 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0014_document_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='VerifierRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='applicability',
            field=models.CharField(choices=[('always', 'Always'), ('optional', 'Optional'), ('conditional', 'Conditional')], default='always', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='partyRole',
            field=models.CharField(choices=[('buyer', 'Buyer / Client'), ('seller', 'Seller / Provider'), ('both', 'Both Parties'), ('staff', 'TrustPay Staff'), ('admin', 'Admin'), ('verifier', 'Assigned Verifier'), ('system', 'System Generated')], default='seller', max_length=32),
        ),
        migrations.AlterField(
            model_name='documentrequirement',
            name='stage',
            field=models.CharField(choices=[('transaction_setup', 'Transaction Setup'), ('buyer_acceptance', 'Buyer Acceptance'), ('seller_acceptance', 'Seller Acceptance'), ('contract_generation', 'Contract Generation'), ('buyer_signature', 'Buyer Signature'), ('seller_signature', 'Seller Signature'), ('funding', 'Escrow Funding'), ('funding_confirmation', 'Funding Confirmation'), ('delivery', 'Seller Delivery / Deliverable Submission'), ('verification', 'Fulfilment Verification'), ('buyer_approval', 'Buyer Approval'), ('release', 'Funds Release'), ('completion', 'Transaction Completion'), ('dispute', 'Dispute')], default='delivery', max_length=64),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='documentTypeDefinition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='escrow.documenttype'),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='verifierRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requirements', to='escrow.verifierrole'),
        ),
    ]
