# Generated by Django 5.2.17 on 2026-08-27 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0018_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buyerAcceptedVersion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sellerAcceptedVersion',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
