# Generated by Django 5.2.17 on 2026-08-27 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0019_transaction_buyeracceptedversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cancellationApprovedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cancellationApprovedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_transaction_cancellations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_party_review', 'Awaiting Party Review'), ('awaiting_buyer_acceptance', 'Awaiting Buyer Acceptance'), ('awaiting_seller_acceptance', 'Awaiting Seller Acceptance'), ('awaiting_kyc', 'Awaiting KYC'), ('contract_pending', 'Contract Pending'), ('awaiting_buyer_signature', 'Awaiting Buyer Signature'), ('awaiting_seller_signature', 'Awaiting Seller Signature'), ('awaiting_funding', 'Awaiting Funding'), ('funding_confirmation_pending', 'Funding Confirmation Pending'), ('funded', 'Funded'), ('in_progress', 'In Progress'), ('awaiting_verification', 'Awaiting Verification'), ('awaiting_buyer_approval', 'Awaiting Buyer Approval'), ('release_pending', 'Release Pending'), ('completed', 'Completed'), ('changes_requested', 'Changes Requested'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('cancellation_pending', 'Cancellation Pending'), ('expired', 'Expired'), ('on_hold', 'On Hold'), ('frozen', 'Frozen'), ('disputed', 'Disputed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], default='draft', max_length=50),
        ),
    ]
