# Generated by Django 5.2.17 on 2026-08-27 01:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0020_transaction_cancellationapprovedat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='assignedVerifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='buyerApprovalRequired',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='buyerComment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='buyerDecision',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='milestone',
            name='buyerDecisionAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='buyerDecisionBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decided_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milestone',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='milestone',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='paidAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='releaseAmount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='milestone',
            name='releaseStatus',
            field=models.CharField(default='not_eligible', max_length=24),
        ),
        migrations.AddField(
            model_name='milestone',
            name='responsibleParticipant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_milestones', to='escrow.userprofile'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='responsibleParty',
            field=models.CharField(choices=[('seller', 'Seller / Provider'), ('buyer', 'Buyer / Client'), ('participant', 'Assigned Participant')], default='seller', max_length=20),
        ),
        migrations.AddField(
            model_name='milestone',
            name='submittedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='submittedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submitted_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='verificationComment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='verificationRequired',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='verifiedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='milestone',
            name='verifiedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_milestones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='milestone',
            name='verifierRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='escrow.verifierrole'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('changes_required', 'Changes Required'), ('approved', 'Approved'), ('release_eligible', 'Release Eligible'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('disputed', 'Disputed')], default='pending', max_length=32),
        ),
    ]
