# Generated by Django 5.2.17 on 2026-08-27 01:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0021_milestone_assignedverifier_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contractType',
            field=models.CharField(default='escrow_agreement', max_length=64),
        ),
        migrations.AddField(
            model_name='contract',
            name='createdBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='effectiveAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='executedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='reference',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='transactionVersion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contract',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('awaiting_buyer_signature', 'Awaiting Buyer Signature'), ('awaiting_seller_signature', 'Awaiting Seller Signature'), ('fully_signed', 'Fully Signed'), ('superseded', 'Superseded'), ('voided', 'Voided'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='generated', max_length=32),
        ),
        migrations.AlterField(
            model_name='contract',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='escrow.transaction'),
        ),
        migrations.CreateModel(
            name='ContractSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contractVersion', models.PositiveIntegerField()),
                ('signerRole', models.CharField(choices=[('buyer', 'Buyer / Client'), ('seller', 'Seller / Provider')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('voided', 'Voided')], default='pending', max_length=16)),
                ('signatureMethod', models.CharField(default='account_confirmation', max_length=40)),
                ('signedAt', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement', models.TextField(blank=True)),
                ('evidenceHash', models.CharField(blank=True, max_length=64)),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('userAgent', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='escrow.contract')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contract_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('contract', 'signerRole'), name='unique_contract_signature_role')],
            },
        ),
    ]
