# Generated by Django 5.2.17 on 2026-08-27 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0022_contract_contracttype_contract_createdby_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondispute',
            name='amountInDispute',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='appealReason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='appealRequestedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='appealRequestedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appealed_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='assignedStaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='category',
            field=models.CharField(choices=[('non_delivery', 'Non-Delivery'), ('incomplete_delivery', 'Incomplete Delivery'), ('quality_issue', 'Quality Issue'), ('incorrect_goods_service', 'Incorrect Goods / Service'), ('milestone_disagreement', 'Milestone Disagreement'), ('payment_issue', 'Payment Issue'), ('contract_terms', 'Contract Terms'), ('fraud', 'Fraud / Suspicious Activity'), ('ownership_document', 'Ownership / Document Issue'), ('cancellation_refund', 'Cancellation / Refund'), ('other', 'Other')], default='other', max_length=40),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='closedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='mediator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mediated_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='escrow.milestone'),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='opposingParty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opposed_transaction_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='escrow.paymentrecord'),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='reference',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='requestedOutcome',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='resolutionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='resolutionNotes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='resolutionType',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='responseDeadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='reviewDeadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='title',
            field=models.CharField(default='Transaction dispute', max_length=255),
        ),
        migrations.AddField(
            model_name='transactiondispute',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transactiondispute',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('awaiting_counterparty', 'Awaiting Counterparty Response'), ('under_review', 'Under Review'), ('evidence_required', 'Evidence Required'), ('mediation', 'Mediation'), ('resolution_pending', 'Resolution Pending'), ('resolved', 'Resolved'), ('appealed', 'Appealed'), ('closed', 'Closed'), ('rejected', 'Rejected / Invalid')], default='open', max_length=32),
        ),
        migrations.CreateModel(
            name='DisputeAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('outcome', models.CharField(blank=True, max_length=40)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='escrow.transactiondispute')),
                ('requestedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolutionType', models.CharField(max_length=40)),
                ('buyerRefundAmount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('sellerReleaseAmount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('notes', models.TextField()),
                ('decidedAt', models.DateTimeField(auto_now_add=True)),
                ('appliedAt', models.DateTimeField(blank=True, null=True)),
                ('decidedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='escrow.transactiondispute')),
            ],
        ),
        migrations.CreateModel(
            name='DisputeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrees', models.BooleanField(blank=True, null=True)),
                ('response', models.TextField()),
                ('proposedSettlement', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='escrow.transactiondispute')),
            ],
        ),
        migrations.CreateModel(
            name='DisputeSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerReleaseAmount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('buyerRefundAmount', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('applied', 'Applied')], default='proposed', max_length=16)),
                ('acceptedByBuyer', models.BooleanField(blank=True, null=True)),
                ('acceptedBySeller', models.BooleanField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='escrow.transactiondispute')),
                ('proposedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
