# Generated by Django 5.2.17 on 2026-08-27 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0023_transactiondispute_amountindispute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequirement',
            name='displayOrder',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='effectiveFrom',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_requirements', to='escrow.milestone'),
        ),
        migrations.AddField(
            model_name='documentrequirement',
            name='ruleVersion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='defaultCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_types', to='escrow.documentcategory'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='verificationCapable',
            field=models.BooleanField(default=True),
        ),
    ]
