# Generated by Django 5.2.17 on 2026-08-27 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0024_documentrequirement_displayorder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='applicantType',
            field=models.CharField(choices=[('individual', 'Individual KYC'), ('business', 'Business KYB')], default='individual', max_length=32),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='authorizedRepresentative',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='backIdImage',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/identification/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='businessAddress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='businessEmail',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='businessPhone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='businessRegistrationNumber',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='countryOfRegistration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='countryOfResidence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='driversLicenseNumber',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='expectedTransactionActivity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='expiryDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='fullLegalName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='gender',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='issueDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='issuingCountry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='lastUpdatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='legalName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='licencePermit',
            field=models.FileField(blank=True, null=True, upload_to='kyc/business/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='natureOfBusiness',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='occupation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='passportNumber',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='passportPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/identification/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='proofOfBusinessAddress',
            field=models.FileField(blank=True, null=True, upload_to='kyc/business/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='registeredAddress',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='registrationCertificate',
            field=models.FileField(blank=True, null=True, upload_to='kyc/business/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='registrationDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='reviewComments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='reviewedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='reviewer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='selfieEvidence',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/identification/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='sourceOfFunds',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='taxDocument',
            field=models.FileField(blank=True, null=True, upload_to='kyc/business/'),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='taxIdentificationNumber',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='tradingName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='kycsubmission',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='party',
            name='complianceNote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='party',
            name='complianceStatus',
            field=models.CharField(choices=[('not_cleared', 'Not Cleared'), ('pending', 'Pending'), ('cleared', 'Cleared'), ('enhanced_review', 'Enhanced Review Required'), ('restricted', 'Restricted'), ('suspended', 'Suspended')], default='not_cleared', max_length=32),
        ),
        migrations.AddField(
            model_name='party',
            name='lastComplianceReviewAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='needsReverification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='party',
            name='partyType',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business / Organisation')], default='individual', max_length=32),
        ),
        migrations.AddField(
            model_name='party',
            name='restrictedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='reverificationDueAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='party',
            name='riskLevel',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical / Restricted')], default='low', max_length=20),
        ),
        migrations.AddField(
            model_name='party',
            name='riskReasons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='party',
            name='suspendedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='idImage',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/identification/'),
        ),
        migrations.AlterField(
            model_name='kycsubmission',
            name='verificationStatus',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('additional_info_required', 'Additional Information Required'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('reverification_required', 'Reverification Required'), ('suspended', 'Suspended')], default='not_started', max_length=32),
        ),
        migrations.CreateModel(
            name='BusinessOwnershipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(max_length=255)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('ownershipPercentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('identificationReference', models.CharField(blank=True, max_length=255)),
                ('verificationStatus', models.CharField(default='pending', max_length=32)),
                ('isActive', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_records', to='escrow.party')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewType', models.CharField(choices=[('individual', 'Individual KYC'), ('business', 'Business KYB')], default='individual', max_length=32)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('decision', models.CharField(blank=True, max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reviews', to='escrow.party')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnhancedDueDiligenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestReason', models.TextField(blank=True)),
                ('requestedAt', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True)),
                ('reviewDecision', models.CharField(default='pending', max_length=32)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edd_records', to='escrow.party')),
                ('requestedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edd_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riskLevel', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical / Restricted')], default='low', max_length=20)),
                ('indicators', models.JSONField(blank=True, default=list)),
                ('source', models.CharField(default='manual_review', max_length=100)),
                ('assessedAt', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True)),
                ('assessedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='escrow.party')),
            ],
        ),
    ]
