# Generated by Django 5.2.17 on 2026-08-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0025_kycsubmission_applicanttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesapalConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=16)),
                ('consumerKeyCiphertext', models.TextField(blank=True)),
                ('consumerSecretCiphertext', models.TextField(blank=True)),
                ('callbackUrl', models.URLField(blank=True)),
                ('ipnUrl', models.URLField(blank=True)),
                ('ipnId', models.CharField(blank=True, max_length=128)),
                ('enabled', models.BooleanField(default=False)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
