# Generated by Django 5.2.17 on 2026-08-30 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0027_documentrequirement_archivedat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dispute_evidence/%Y/%m/%d/')),
                ('documentType', models.CharField(help_text='e.g., invoice, receipt, photo, screenshot', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional context about the evidence')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='escrow.transactiondispute')),
                ('uploadedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
