# Generated by Django 5.2.17 on 2026-09-10 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0028_disputeevidence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, unique=True)),
                ('externalReference', models.CharField(blank=True, max_length=128)),
                ('buyerName', models.CharField(blank=True, max_length=255)),
                ('buyerEmail', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=10)),
                ('successUrl', models.URLField(blank=True)),
                ('cancelUrl', models.URLField(blank=True)),
                ('webhookUrl', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('payment_submitted', 'Payment Submitted'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='open', max_length=32)),
                ('expiresAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkout_sessions', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_sessions', to='escrow.transaction')),
            ],
        ),
    ]
