# Generated by Django 5.2.17 on 2026-09-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0029_checkoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='specialTerms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
