# Generated by Django 5.2.17 on 2026-09-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0030_transaction_specialterms'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='additionalTerms',
            field=models.TextField(blank=True),
        ),
    ]
