from django.urls import path
from . import views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('', views.landing_view, name='landing'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('transactions/', views.transactions_view, name='transactions'),
    path('transactions/new/', views.transaction_create_view, name='transaction-create'),
    path('transactions/<str:transaction_id>/', views.transaction_detail_view, name='transaction-detail'),
    path('transactions/<str:transaction_id>/fund/', views.payment_submit_view, name='payment-submit'),
    path('transactions/<str:transaction_id>/<str:action>/', views.transaction_action_view, name='transaction-action'),
    path('kyc/submit/', views.kyc_submit_view, name='kyc-submit'),
    path('kyc/', views.kyc_view, name='kyc'),
    path('kyc/overview/', views.kyc_overview_view, name='kyc-overview'),
    path('kyc/<str:party_id>/review/', views.kyc_review_view, name='kyc-review'),
    path('documents/', views.documents_view, name='documents'),
    path('transactions/<str:transaction_id>/documents/new/', views.document_upload_view, name='document-upload'),
    path('documents/<str:document_id>/review/', views.document_review_view, name='document-review'),
    path('transaction-documents/', views.document_requirements_view, name='document-requirements'),
    path('transaction-documents/categories/', views.document_categories_view, name='document-categories'),
    path('transaction-documents/types/', views.document_types_view, name='document-types'),
    path('transaction-documents/types/new/', views.document_type_create_view, name='document-type-create'),
    path('transaction-documents/verifier-roles/', views.verifier_roles_view, name='verifier-roles'),
    path('transaction-documents/verifier-roles/new/', views.verifier_role_create_view, name='verifier-role-create'),
    path('transaction-documents/categories/new/', views.document_category_create_view, name='document-category-create'),
    path('transaction-documents/requirements/new/', views.document_requirement_create_view, name='document-requirement-create'),
    path('transaction-documents/requirements/<int:requirement_id>/edit/', views.document_requirement_edit_view, name='document-requirement-edit'),
    path('transaction-documents/requirements/<int:requirement_id>/duplicate/', views.document_requirement_duplicate_view, name='document-requirement-duplicate'),
    path('transaction-documents/requirements/<int:requirement_id>/toggle-active/', views.document_requirement_toggle_active_view, name='document-requirement-toggle-active'),
    path('transaction-documents/requirements/<int:requirement_id>/delete/', views.document_requirement_delete_view, name='document-requirement-delete'),
    path('transactions/<str:transaction_id>/milestones/new/', views.milestone_create_view, name='milestone-create'),
    path('milestones/', views.milestones_view, name='milestones'),
    path('milestones/<int:milestone_id>/', views.milestone_detail_view, name='milestone-detail'),
    path('milestones/<int:milestone_id>/<str:action>/', views.milestone_action_view, name='milestone-action'),
        path('contracts/', views.contracts_view, name='contracts'),
        path('contracts/<int:contract_id>/', views.contract_detail_view, name='contract-detail'),
        path('disputes/', views.disputes_view, name='disputes'),
        path('disputes/new/', views.dispute_create_view, name='dispute-create'),
        path('disputes/<int:dispute_id>/', views.dispute_detail_view, name='dispute-detail'),
        path('disputes/<int:dispute_id>/<str:action>/', views.dispute_action_view, name='dispute-action'),
    path('docs/', views.api_docs_view, name='api-docs'),
    path('payments/', views.payments_overview_view, name='payments-overview'),
    path('payments/verification/', views.payment_verification_view, name='payment-verification'),
    path('payments/<int:payment_id>/review/', views.payment_decision_view, name='payment-review'),
    path('payments/ledger/', views.escrow_ledger_view, name='escrow-ledger'),
    path('payments/reconciliation/', views.reconciliation_view, name='payment-reconciliation'),
    path('audit/', views.audit_console_view, name='audit-console'),
    path('payments/pesapal/', views.pesapal_settings_view, name='pesapal-settings'),
    path('settings/', views.settings_view, name='settings'),
    path('transactions/<str:transaction_id>/pay/pesapal/', views.pesapal_payment_view, name='pesapal-payment'),
    path('payments/pesapal/ipn/', views.pesapal_ipn_view, name='pesapal-ipn'),

    path('auth/login/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('auth/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('kyc/pending', views.PendingKycList.as_view()),
    path('kyc/participant/<str:party_id>/profile', views.ParticipantProfile.as_view()),
    path('kyc/participant/<str:party_id>/auto-verify', views.auto_verify),
    path('kyc/participant/<str:party_id>/verify', views.verify_party),
    path('kyc/participant/<str:party_id>/unverify', views.unverify_party),

    path('transactions-api', views.TransactionList.as_view()),
    path('transactions-api/<str:txn_id>', views.TransactionDetail.as_view()),
]
