# Generated by Django 6.1 on 2026-08-23 03:21

import django.db.models.deletion
from django.db import migrations, models


def create_modules_and_map_permissions(apps, schema_editor):
    Module = apps.get_model('users', 'Module')
    module_cache = {}
    with schema_editor.connection.cursor() as cursor:
        cursor.execute('SELECT id, module_id FROM users_permission')
        permissions = cursor.fetchall()
    for permission_id, old_module in permissions:
        module_code = str(old_module or 'general').strip().lower().replace(' ', '_')
        module_name = str(old_module or 'General').strip().title()
        module = module_cache.get(module_code)
        if not module:
            module, _ = Module.objects.get_or_create(code=module_code, defaults={'name': module_name})
            module_cache[module_code] = module
        with schema_editor.connection.cursor() as cursor:
            cursor.execute('UPDATE users_permission SET module_id = %s WHERE id = %s', [module.pk, permission_id])


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_rbac'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='users.module'),
        ),
        migrations.RunPython(create_modules_and_map_permissions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permissions', to='users.module'),
        ),
    ]
