# Generated by Django 5.2.17 on 2026-08-27 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_apikey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailNotifications', models.BooleanField(default=True)),
                ('paymentNotifications', models.BooleanField(default=True)),
                ('disputeNotifications', models.BooleanField(default=True)),
                ('marketingNotifications', models.BooleanField(default=False)),
                ('dashboardDensity', models.CharField(choices=[('comfortable', 'Comfortable'), ('compact', 'Compact')], default='comfortable', max_length=16)),
                ('preferredCurrency', models.CharField(default='UGX', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
