# Generated by Django 5.2.17 on 2026-08-27 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_legacy_notification_keys(apps, schema_editor):
    Notification = apps.get_model('users', 'Notification')
    for notification in Notification.objects.filter(event_code='system.notice', related_object_id=''):
        notification.related_object_id = f'legacy-{notification.pk}'
        notification.save(update_fields=['related_object_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('escrow', '0026_pesapalconfiguration'),
        ('users', '0008_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=20)),
                ('provider', models.CharField(default='development', max_length=80)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('retry_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('transaction', 'Transactions'), ('payment', 'Payments'), ('contract', 'Contracts'), ('milestone', 'Milestones'), ('dispute', 'Disputes'), ('compliance', 'KYC / Compliance'), ('security', 'Security'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_channels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='notification',
            name='event_code',
            field=models.CharField(default='system.notice', max_length=100),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='escrow.party'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('informational', 'Informational'), ('action_required', 'Action Required'), ('important', 'Important'), ('urgent', 'Urgent')], default='informational', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='notification',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='escrow.transaction'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='complianceNotifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='contractNotifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='milestoneNotifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='securityNotifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='transactionNotifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='level',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Important'), ('danger', 'Urgent')], default='info', max_length=16),
        ),
        migrations.RunPython(preserve_legacy_notification_keys, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('user', 'event_code', 'related_object_type', 'related_object_id'), name='unique_user_notification_event_object'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='users.notification'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'channel'), name='unique_notification_delivery_channel'),
        ),
    ]
